### ISSUE TITLE
Image management

### ISSUE THREAD

**Issue by josephernest** [josephernest/bigpicture.js#12]

**Comment by funnyflowerpot** [comment]
Dear @josephernest, thanks for creating this library, it works well and is much fun!
I have a project in mind where I need exactly this functionality. However, support for (bitmap) images would also be necessary. There are quite a few new problems one has to take care of when handling images. Do you know a library that supports image integration and would work well with bigpicture.js? I expect that a server-client-architecture will be necessary (I saw your AReallyBigPage project), but that's doable.
